services:
  proxmox-lxc-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxmox-lxc-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3

